id: sync_flows_from_git
namespace: system
tasks:
  - id: git
    type: io.kestra.plugin.git.SyncFlows
    gitDirectory: kestra-flows
    targetNamespace: zoomcamp
    includeChildNamespaces: true
    delete: true
    url: https://github.com/MaryMash/zoom_camp_week_2_hw.git
    branch: main
    username: MaryMash
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    dryRun: false

triggers:
  - id: every_full_hour
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"